# All values within {}'s must be replaced by the user
# {YYYYMMDD} ~ 20190530
# {expid} ~ e5303_m21c_jan18
# {timeseries_src_dir} ~ the full path to the directory src directory (i.e. $NOBACKUP/pyradmon/offline/timeseries/src/)
# {expname} ~ can be anything, ex: m21c_radmon

 
#
startdate: 20190501 000000
enddate:  20190531 180000

#
expid: e5303_m21c_jan18
data_dirbase: /home/dao_ops/m21c/archive/e5303_m21c_jan18/obs
runbase: /home/dao_ops/e5303_m21c_jan18/run/
mstorage: /home/dao_ops/e5303_m21c_jan18/run/mstorage.arc # $runbase/mstorage.arc
arcbase: /home/dao_ops/m21c/archive/ # M21C Specific

#
expbase: /discover/nobackup/sicohen/RADMON/develop/pyradmon/offline/timeseries/src/m21c_radmon/
scratch_dir: /discover/nobackup/sicohen/RADMON/develop/pyradmon/offline/timeseries/src/m21c_radmon/scratch/
output_dir: /discover/nobackup/sicohen/RADMON/develop/pyradmon/offline/timeseries/src/m21c_radmon/radmon/

#
rcfile: /discover/nobackup/sicohen/RADMON/develop/pyradmon/offline/timeseries/src/test_config_yaml_path.yaml #path to this yaml file

# Optional ~ see the satlist.yaml for insturment list (ex: amsua_n15)
instruments: amsua_n15 


# DEFAULT VALUES ~ No Edits Required
pyradmon: /home/dao_ops/pyradmon/
bin2txt_exec: /home/dao_ops/GEOSadas-5_29_5_SLES15/GEOSadas/install/bin/gsidiag_bin2txt.x
gsidiagsrc: /home/dao_ops/GEOSadas-5_29_5_SLES15/GEOSadas/install/etc/gsidiags.rc

## Polar
#rename_date_dir: current
#scp_userhost: sicohen@polar
#scp_path: /www/html/intranet/personnel/sicohen/m21c/radmon_data/
