# All values within {}'s must be replaced by the user
# {YYYYMMDD} ~ 20190530
# {path_to_pyradmon} ~ Users local clone of pyradmon https://github.com/GEOS-ESM/pyradmon/tree/develop
# {expid} ~ e5303_m21c_jan18
# {timeseries_src_dir} ~ the full path to the directory src directory (i.e. $NOBACKUP/pyradmon/offline/timeseries/src/)
# {expname} ~ can be anything, ex: m21c_radmon
# yaml file name ~ test_config_yaml_path.yaml
 
#
startdate: {YYYYMMDD} 000000
enddate:  {YYYYMMDD} 180000

# Users local clone of pyradmon https://github.com/GEOS-ESM/pyradmon/tree/develop
pyradmon: {path_to_pyradmon}

#
expid: {expid}
data_dirbase: /home/dao_ops/m21c/archive/{expid}/obs
runbase: /home/dao_ops/{expid}/run/
mstorage: /home/dao_ops/{expid}/run/mstorage.arc # $runbase/mstorage.arc
arcbase: /home/dao_ops/m21c/archive/ # M21C Specific

#
expbase: {timeseries_src_dir}/{expname}
scratch_dir: {expbase}/scratch
output_dir: {expbase}/radmon

#
rcfile: {timeseries_src_dir}/test_config_yaml_path.yaml #{yaml file name} #path to this yaml file

# Optional ~ see the satlist.yaml for insturment list (ex: amsua_n15)
instruments: amsua_n15 


# DEFAULT VALUES ~ No Edits Required
bin2txt_exec: /home/dao_ops/GEOSadas-5_29_5_SLES15/GEOSadas/install/bin/gsidiag_bin2txt.x
gsidiagsrc: /home/dao_ops/GEOSadas-5_29_5_SLES15/GEOSadas/install/etc/gsidiags.rc

## Polar
#rename_date_dir: current
#scp_userhost: sicohen@polar
#scp_path: /www/html/intranet/personnel/sicohen/m21c/radmon_data/
