# test_config_yaml_path.skeleton.yaml:
# ------------------------------------

# Section 0: Variable descriptions
# --------------------------------
# {YYYYMMDD} ~ 20190530
# {HH} ~ 00
# {path_to_pyradmon} ~ Users local clone of pyradmon 
# {expid} ~ e5303_m21c_jan18
# yaml file name ~ test_config_yaml_path.yaml
# --------------------------------



# Section 1: Date Range
# ---------------------
startdate: {YYYYMMDD} {HH}0000
enddate:  {YYYYMMDD} {HH}0000

# Section 2: Input Observation Data (directory paths) ~ *will be specific* to m2, geosit, m21c, and the expid (stream)
# --------------------------------------------------------------------------------------------------------------------
expid: {expid}
data_dirbase: /home/dao_ops/m21c/archive/{expid}/obs
runbase: /home/dao_ops/{expid}/run/
mstorage: /home/dao_ops/{expid}/run/mstorage.arc
arcbase: /home/dao_ops/m21c/archive/ 

# Section 3: Output Directories
# -----------------------------
expbase: /discover/nobackup/{user_id}/radmon/pyradmon-dao-ops-pointer/offline/timeseries/src/m21c_radmon
scratch_dir: /discover/nobackup/{user_id}/radmon/pyradmon-dao-ops-pointer/offline/timeseries/src/m21c_radmon/scratch
output_dir: /discover/nobackup/{user_id}/radmon/pyradmon-dao-ops-pointer/offline/timeseries/src/m21c_radmon/radmon

# Section 4: rcfile is the path to this yaml file (the one you have open and are editing that will be used as the [user_input_yaml])
# ----------------------------------------------------------------------------------------------------------------------------------
rcfile: /discover/nobackup/{user_id}/radmon/pyradmon-dao-ops-pointer/offline/timeseries/src/user_input_yaml.yaml

# Section 5: (Optional) Specific instruments - one, multiple or all
# Optional ~ you may leave this commented out if you want to run for all. See the satlist.yaml for instrument list (ex: amsua_n15).
# ---------------------------------------------------------------------------------------------------------------------------------
#instruments: amsua_n15            # run one
#instruments: amsua_n15,amsua_n16  # run multiple - separate instruments by comma 
#instruments:                      # run all (leave commented out)

# Section 6: (Optional) Polar
# ---------------------------
#rename_date_dir: current
#scp_userhost: {user_id}@polar
#scp_path: /www/html/intranet/personnel/{user_id}/{dir}

# Section 7: (No edits) Pyradmon Pointer
# Section dao_ops version of pyradmon - scripts will point to this rather than the scripts in the locally installed/cloned pyradmon
# ---------------------------------------------------------------------------------------------------------------------------------
pyradmon: /home/dao_ops/pyradmon/

  
# Section 8: (No edits) Default gsidiag exec and rc file
# ------------------------------------------------------
bin2txt_exec: /home/dao_ops/GEOSadas-5_29_5_SLES15/GEOSadas/install/bin/gsidiag_bin2txt.x
gsidiagsrc: /home/dao_ops/GEOSadas-5_29_5_SLES15/GEOSadas/install/etc/gsidiags.rc
  