plot_config:
    xrange: [-180,180]
    yrange: [-90,90]
    rcparams:
#        figure.figsize: [4.8,3.6]
        figure.figsize: [6.4,4.8]
        font.size: 12
        axes.titlesize: 12
plots:
    obs_all:
        var: 'obs'
        cmap: 'viridis'
        chan: used
        mask: '(obs > 50) & (obs < 400)'
        markersize: 10
        plot_title:  "$psatellite $psensor\n$hour UTC $day $shortmon $year\nAll Observations, Channel $ch $chinfo"
        cbar_title:  "Brightness Temperature (K)\nnobs=$nobs, avg=$avg, std=$std"
        filename: "tbobs.${psensor}_$psatellite.${year}${mon}${day}_${hour}z.allsfc.allarea.allday.qc0.$ch.png"
    obs_used:
        var: 'obs'
        cmap: 'viridis'
        chan: used
        mask: '(obs > 50) & (obs < 400) & (used == 1)'
        markersize: 10
        plot_title:  "$psatellite $psensor\n$hour UTC $day $shortmon $year\nUsed Observations, Channel $ch $chinfo"
        cbar_title:  "Brightness Temperature (K)\nnobs=$nobs, avg=$avg, std=$std"
        filename: "tbobs.${psensor}_$psatellite.${year}${mon}${day}_${hour}z.allsfc.allarea.allday.qc1.$ch.png"
    omfbc_all:
        var: 'omfbc'
        cmap: 'coolwarm'
        chan: used
        mask: '(obs > 50) & (obs < 400)'
        markersize: 10
        cbar_title:  "Brightness Temperature O-F w/ BC (K)\nnobs=$nobs, avg=$avg, std=$std"
        cbar_style:  'centerzero'
        cbar_min: -10
        cbar_max: 10
        plot_title:  "$psatellite $psensor\n$hour UTC $day $shortmon $year\nAll Observations, Channel $ch $chinfo"
        filename: "omgbc.${psensor}_$psatellite.${year}${mon}${day}_${hour}z.allsfc.allarea.allday.qc0.$ch.png"

    omfbc_used:
        var: 'omfbc'
        cmap: 'coolwarm'
        chan: used
        mask: '(obs > 50) & (obs < 400) & (used == 1)'
        markersize: 10
        cbar_title:  "Brightness Temperature O-F w/ BC (K)\nnobs=$nobs, avg=$avg, std=$std"
        cbar_style:  'centerzero'
        plot_title:  "$psatellite $psensor\n$hour UTC $day $shortmon $year\nUsed Observations, Channel $ch $chinfo"
        filename: "omgbc.${psensor}_$psatellite.${year}${mon}${day}_${hour}z.allsfc.allarea.allday.qc1.$ch.png"

    omfnbc_all:
        var: 'omfnbc'
        cmap: 'coolwarm'
        chan: used
        mask: '(obs > 50) & (obs < 400)'
        markersize: 10
        cbar_title:  "Brightness Temperature O-F w/o BC (K)\nnobs=$nobs, avg=$avg, std=$std"
        cbar_style:  'centerzero'
        cbar_min: -10
        cbar_max: 10
        plot_title:  "$psatellite $psensor\n$hour UTC $day $shortmon $year\nAll Observations, Channel $ch $chinfo"
        filename: "omgnbc.${psensor}_$psatellite.${year}${mon}${day}_${hour}z.allsfc.allarea.allday.qc0.$ch.png"

    omfnbc_used:
        var: 'omfnbc'
        cmap: 'coolwarm'
        chan: used
        mask: '(obs > 50) & (obs < 400) & (used == 1)'
        markersize: 10
        cbar_title:  "Brightness Temperature O-F w/o BC (K)\nnobs=$nobs, avg=$avg, std=$std"
        cbar_style:  'centerzero'
        plot_title:  "$psatellite $psensor\n$hour UTC $day $shortmon $year\nUsed Observations, Channel $ch $chinfo"
        filename: "omgnbc.${psensor}_$psatellite.${year}${mon}${day}_${hour}z.allsfc.allarea.allday.qc1.$ch.png"

    bc_all:
        var: 'bc'
        cmap: 'coolwarm'
        chan: used
        mask: '(obs > 50) & (obs < 400)'
        markersize: 10
        cbar_title:  "Bias Correction (K)\nnobs=$nobs, avg=$avg, std=$std"
        cbar_style:  'centerzero'
        plot_title:  "$psatellite $psensor\n$hour UTC $day $shortmon $year\nAll Observations, Channel $ch $chinfo"
        filename: "totbc.${psensor}_$psatellite.${year}${mon}${day}_${hour}z.allsfc.allarea.allday.qc0.$ch.png"

    bc_used:
        var: 'bc'
        cmap: 'coolwarm'
        chan: used
        mask: '(obs > 50) & (obs < 400) & (used == 1)'
        markersize: 10
        cbar_title:  "Bias Correction (K)\nnobs=$nobs, avg=$avg, std=$std"
        cbar_style:  'centerzero'
        plot_title:  "$psatellite $psensor\n$hour UTC $day $shortmon $year\nUsed Observations, Channel $ch $chinfo"
        filename: "totbc.${psensor}_$psatellite.${year}${mon}${day}_${hour}z.allsfc.allarea.allday.qc1.$ch.png"

