PYRADMON: the path to the pyradmon/offline/spatial/src directory
EXPID: expirement id
Date: YYYYMMDD
hour: HH

PYRADMON: /discover/nobackup/sicohen/RADMON/develop/pyradmon/offline/spatial/src
EXPID:
Date:
hour:


obstypes: [atms', 'amsr2', 'amsua', 'amsua_n15', 'avhrr', 'gmi', 'hirs', 'mhs', 'seviri', 'ssmis', 'cris', 'airs', 'iasi']

obstypes:
  - atms 
  - amsr2 
  - amsua
  - amsua_n15
  - avhrr
  - gmi
  - hirs
  - mhs
  - seviri
  - ssmis
  - cris
  - airs
  - iasi