pyradmon: /home/dao_ops/pyradmon/
#pyradmon: /discover/nobackup/projects/gmao/geos-it/mchattop/pyradmon

expid: e5303_m21c_jan18
expbase: /discover/nobackup/sicohen/RADMON/offline/work/r21c/TBR/radmon/time_series/m21c_radmon/
arcbase: /home/dao_ops/m21c/archive/
data_dirbase: /home/dao_ops/m21c/archive/e5303_m21c_jan18/obs
startdate: 20190530 000000
enddate:  20190531 180000

scratch_dir: /discover/nobackup/sicohen/RADMON/offline/work/r21c/TBR/radmon/time_series/m21c_radmon/scratch
output_dir: /discover/nobackup/sicohen/RADMON/offline/work/r21c/TBR/radmon/time_series/m21c_radmon/radmon

#optional: ... are they???
mstorage: /home/dao_ops/e5303_m21c_jan18/run/mstorage.arc
#instruments: amsua_n15
bin2txt_exec: /home/dao_ops/GEOSadas-5_29_5_SLES15/GEOSadas/install/bin/gsidiag_bin2txt.x
bin2txt_nl: /discover/nobackup/sicohen/RADMON/offline/work/r21c/TBR/radmon/time_series/m21c_radmon/radmon_diag_bin2txt.nl
#rename_date_dir: current
scp_userhost: sicohen@polar
scp_path: /www/html/intranet/personnel/sicohen/m21c/radmon_data/
gsidiagsrc: /home/dao_ops/GEOSadas-5_29_5_SLES15/GEOSadas/install/etc/gsidiags.rc