pyradmon: /home/dao_ops/pyradmon/
#pyradmon: /discover/nobackup/projects/gmao/geos-it/mchattop/pyradmon
#pyradmon: /discover/nobackup/sicohen/RADMON/offline/work/r21c/TBR/radmon/time_series
expid: e5303_m21c_jan18
expbase: /discover/nobackup/sicohen/RADMON/develop/pyradmon/offline/timeseries/src/m21c_radmon/
wrkdir: /discover/nobackup/sicohen/RADMON/develop/pyradmon/offline/timeseries/src/m21c_radmon/
arcbase: /home/dao_ops/m21c/archive/
data_dirbase: /home/dao_ops/m21c/archive/e5303_m21c_jan18/obs
startdate: 20190530 000000
enddate:  20190531 180000

expbase: /discover/nobackup/sicohen/RADMON/develop/pyradmon/offline/timeseries/src/m21c_radmon/
scratch_dir: /discover/nobackup/sicohen/RADMON/develop/pyradmon/offline/timeseries/src/m21c_radmon/scratch
output_dir: /discover/nobackup/sicohen/RADMON/develop/pyradmon/offline/timeseries/src/m21c_radmon/radmon
runbase: /home/dao_ops/e5303_m21c_jan18/run/

#optional: ... are they???
mstorage: /home/dao_ops/e5303_m21c_jan18/run/mstorage.arc
instruments: amsua_n15
bin2txt_exec: /home/dao_ops/GEOSadas-5_29_5_SLES15/GEOSadas/install/bin/gsidiag_bin2txt.x
bin2txt_nl: /discover/nobackup/sicohen/RADMON/develop/pyradmon/offline/timeseries/src/m21c_radmon/radmon_diag_bin2txt.nl
bin2txtnl: /home/dao_ops/pyradmon/pyradmon/gsidiag/gsidiag_bin2txt/gsidiag_bin2txt.nl
#rename_date_dir: current
#scp_userhost: sicohen@polar
#scp_path: /www/html/intranet/personnel/sicohen/m21c/radmon_data/
gsidiagsrc: /home/dao_ops/GEOSadas-5_29_5_SLES15/GEOSadas/install/etc/gsidiags.rc
rcfile: /discover/nobackup/sicohen/RADMON/develop/pyradmon/offline/timeseries/src/test_config_yaml_path.yaml
bin2txt_nl: /discover/nobackup/sicohen/RADMON/develop/pyradmon/offline/timeseries/src/m21c_radmon/radmon_diag_bin2txt.nl
